version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    environment:
      - PYTHON 
      - TZ=America/New_York
    ports:
      - 8888:8888
      - 4040:4040
    ulimits:
      nofile:
        soft: "500000"
        hard: "500000"
    tty: true
          
